In [1]:
import torch
import numpy as np
import time
from torch.nn import functional as F

In [3]:
x = torch.tensor([-0.05], dtype=torch.float32)
sig = F.sigmoid(x)
print(sig)

tensor([0.4875])


In [4]:
x = torch.tensor([10], dtype=torch.float32)
tanh = F.tanh(x)
print(tanh)

tensor([1.])


In [5]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([ 78,  22,  90, -85,  90,   8])

In [6]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [7]:
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [7]:
empties = torch.empty(2,3)
empties

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
arange = torch.arange(4)
arange

tensor([0, 1, 2, 3])

In [9]:
linespace = torch.linspace(3, 10, steps=5)
linespace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [10]:
logspace = torch.logspace(start=-10, end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [11]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [12]:
a = torch.empty((2,3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [2]:
device = 'mps' if torch.backends.mps.is_available() else 'CPU'
print(device)

mps


In [7]:
import time

start_time = time.time()
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f'{elapsed_time: .8f}')

 0.00056005


In [3]:
import numpy as np

torch_rand1 = torch.rand(200, 200, 200, 200).to(device)
torch_rand2 = torch.rand(200, 200, 200, 200).to(device)

np_rand1 = torch.rand(200, 200, 200, 200)
np_rand2 = torch.rand(200, 200, 200, 200)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()
elapsed_time = end_time - start_time
print(f'GPU: {elapsed_time: .8f}')

start_time = time.time()

np_rand = np.multiply(np_rand1, np_rand2)

end_time = time.time()
elapsed_time = end_time - start_time
print(f'CPU: {elapsed_time: .8f}')

GPU:  0.25220609
CPU:  56.33992696


In [6]:
#torch.multimonial for probability 1 

probabilities = torch.tensor([0.4, 0.6])

samples = torch.multinomial(probabilities, num_samples=10, replacement=True)

print(samples)

tensor([1, 1, 1, 1, 0, 1, 1, 1, 1, 1])


In [9]:
cat_tensor = torch.tensor([1, 2, 3, 4])

out = torch.cat((cat_tensor, torch.tensor([5])), dim=0)

out

tensor([1, 2, 3, 4, 5])

In [10]:
#torch.tril which means triangle lower (prediction of future)

out = torch.tril(torch.ones(5,5))

out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [11]:
#torch.triu which means triangle upper (prediction of future)

out = torch.triu(torch.ones(5,5))

out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [12]:
#torch.masked_fill (Exponential fills of given input, which is constant 2.71)

out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))

out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [13]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [18]:
input = torch.zeros(2, 3, 4)

print(input.shape)

output = input.transpose(0, 2)

output.shape

torch.Size([2, 3, 4])


torch.Size([4, 3, 2])

In [19]:
#torch.stack -- stack the tensors along a new dimension

tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 3])
tensor3 = torch.tensor([6, 9, 3])

stacked_tensor = torch.stack((tensor1, tensor2, tensor3))

stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 3],
        [6, 9, 3]])

In [20]:
#nn.linear() -- 

import torch.nn as nn

sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias=False)

print(linear(sample))

tensor([-6.5271, -3.7748,  3.9930], grad_fn=<SqueezeBackward4>)


In [21]:
#softmax - Exponentiates the given input , add them together and divide each exp_num by the total

import torch.nn.functional as F

input = torch.tensor([1.0, 3.0, 9.0, 5.0])

soft_max_op = F.softmax(input, dim=0)

print(soft_max_op)

tensor([3.2852e-04, 2.4275e-03, 9.7931e-01, 1.7937e-02])


In [22]:
# Define the size of the vocabulary and the dimension of the embeddings
vocab_size = 1000
embedding_dim = 100

# Create an nn.Embedding layer
embedding_layer = nn.Embedding(num_embeddings=vocab_size, embedding_dim=embedding_dim)

# Input data (categorical indices)
input_data = torch.tensor([1, 5, 3, 2, 7])

# Pass the input data through the embedding layer to get embeddings
embeddings = embedding_layer(input_data)

print(embeddings)

tensor([[ 4.2444e-01, -6.9652e-01, -1.7187e+00, -1.0558e-01,  1.2768e+00,
          3.8173e-01,  1.1419e+00, -1.2254e+00, -8.3757e-01,  3.8385e-02,
          7.8659e-02, -1.5304e+00, -5.8135e-01, -5.1524e-01, -1.6842e+00,
          7.0204e-01,  3.3022e-01, -1.3359e-01,  6.4285e-01,  5.5127e-01,
          1.6545e+00,  1.6382e-01,  4.8551e-01, -1.6015e+00,  5.7424e-01,
         -2.4198e-01, -1.0222e+00, -2.0325e-01,  1.7785e+00,  6.7988e-01,
         -2.5440e-01,  1.7606e-01,  2.2031e+00, -5.7443e-01,  2.1714e+00,
         -9.9938e-01, -1.6106e+00, -1.2531e+00,  2.9461e-02, -5.2000e-01,
         -8.7881e-01, -1.2239e+00,  8.8053e-01, -2.3515e-01,  9.1455e-01,
         -5.2171e-01, -5.1176e-01, -4.8715e-01, -1.5512e+00,  1.9252e+00,
          3.5578e-01, -3.3600e-01,  9.5213e-01, -1.1835e+00,  7.4993e-01,
          1.2109e+00,  1.3810e+00,  7.8436e-01, -2.8335e-01,  4.2173e-01,
         -9.4256e-01,  5.1188e-02,  1.6399e+00, -2.1817e-01,  1.4837e+00,
         -4.5616e-02,  4.0023e-01, -1.

In [23]:
# Create two 3-dimensional tensors (batch_size=3, rows=2, columns=2)
batch_size = 3
A = torch.rand(batch_size, 2, 2)  # Random 2x2 matrices, batched
B = torch.rand(2, 2)  # Random 2x2 matrix

# Perform batched matrix multiplication using torch.matmul
result = torch.matmul(A, B)

# Print the original tensors and the result
print("Tensor A (batched):\n", A)
print("\nTensor B:\n", B)
print("\nResult (batched matrix multiplication):\n", result)

Tensor A (batched):
 tensor([[[0.3515, 0.1936],
         [0.7308, 0.3949]],

        [[0.4989, 0.3970],
         [0.4264, 0.8829]],

        [[0.1744, 0.2855],
         [0.7300, 0.4070]]])

Tensor B:
 tensor([[0.0644, 0.9779],
        [0.3493, 0.2906]])

Result (batched matrix multiplication):
 tensor([[[0.0903, 0.4000],
         [0.1850, 0.8293]],

        [[0.1708, 0.6032],
         [0.3358, 0.6735]],

        [[0.1109, 0.2535],
         [0.1892, 0.8321]]])


In [28]:
int_64 = torch.randint(1, (3, 2)).float()

float_32 = torch.rand(2, 3)

print(int_64.dtype, float_32.dtype)

res = torch.matmul(int_64, float_32)

print(res)

torch.float32 torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [3]:
a = torch.rand(2, 3, 5)
print(a.shape)
x, y, z = a.shape
a = a.view(x, y, z)

print(a.shape)

torch.Size([2, 3, 5])
torch.Size([2, 3, 5])
